import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import axios from "axios";


const API =
"https://ai-interview-copilot-1-a7tr.onrender.com/api/hr";



export default function HRResult(){


const navigate = useNavigate();

const location = useLocation();


const [loading,setLoading]=useState(true);

const [report,setReport]=useState(null);






useEffect(()=>{


const loadReport=async()=>{


try{


const interviewId =
location.state?.interviewId;



if(!interviewId){

navigate("/dashboard");

return;

}




const token =
localStorage.getItem("token");



const res =
await axios.get(

`${API}/result/${interviewId}`,

{

headers:{

Authorization:
`Bearer ${token}`

}

}

);




const data = res.data.report || res.data.interview || res.data;

setReport(
data
);



setLoading(false);



}

catch(err){

console.log(err);

navigate("/dashboard");

}


};



loadReport();


},[]);







if(loading){


return (

<div className="
min-h-screen
flex
items-center
justify-center
bg-slate-950
text-white
">


<h1 className="text-3xl">
Generating AI Report...
</h1>


</div>

);


}





if(!report)
return null;








const skills=[


{
name:"Communication",
value:report.communication
},


{
name:"Grammar",
value:report.grammar
},


{
name:"Confidence",
value:report.confidence
},


{
name:"Relevance",
value:report.relevance
},


{
name:"Professionalism",
value:report.professionalism
}


];








return (

<div className="
min-h-screen
bg-slate-950
text-white
">


<div className="
max-w-6xl
mx-auto
px-6
py-10
">



<h1 className="
text-4xl
font-bold
text-center
mb-10
">

🤖 AI HR Interview Report

</h1>





{/* OVERALL SCORE */}


<div className="
bg-slate-900
rounded-2xl
p-8
mb-8
text-center
">


<h2 className="text-2xl font-bold mb-5">

Overall Score

</h2>


<div className="
text-7xl
font-bold
text-green-400
">

{report.score || 0}/100


</div>


<p className="text-gray-400 mt-3">

Generated by Groq AI Analysis

</p>


</div>







{/* SKILLS */}


<div className="
grid
md:grid-cols-2
gap-6
">


{

skills.map((skill,index)=>(


<div
key={index}
className="
bg-slate-900
p-6
rounded-xl
"
>


<div className="
flex
justify-between
mb-3
">


<h3 className="font-bold">

{skill.name}

</h3>


<span>

{skill.value || 0}/20

</span>


</div>




<div className="
w-full
bg-slate-700
h-3
rounded-full
">


<div

className="
bg-indigo-500
h-3
rounded-full
"

style={{

width:
`${(skill.value/20)*100 || 0}%`

}}

/>


</div>


</div>


))


}


</div>









{/* FEEDBACK */}


<div className="
bg-slate-900
rounded-xl
p-8
mt-8
">


<h2 className="
text-2xl
font-bold
mb-4
">

AI Feedback

</h2>


<p className="text-gray-300 leading-8">

{report.feedback}

</p>


</div>









{/* BETTER ANSWER */}


<div className="
bg-slate-900
rounded-xl
p-8
mt-8
">


<h2 className="
text-2xl
font-bold
mb-4
">

Suggested Better Answer

</h2>


<p className="
text-gray-300
leading-8
">

{report.betterAnswer}

</p>


</div>








<div className="
grid
md:grid-cols-2
gap-6
mt-8
">


<div className="
bg-slate-900
p-6
rounded-xl
">


<h2 className="
text-2xl
text-green-400
font-bold
mb-5
">

💪 Strengths

</h2>


{
report.strengths?.map(
(s,i)=>(

<p
key={i}
className="
bg-green-900/30
p-3
rounded-lg
mb-3
"
>

✅ {s}

</p>

)

)
}



</div>








<div className="
bg-slate-900
p-6
rounded-xl
">


<h2 className="
text-2xl
text-red-400
font-bold
mb-5
">

📉 Weaknesses

</h2>


{

report.weaknesses?.map(
(w,i)=>(

<p
key={i}
className="
bg-red-900/30
p-3
rounded-lg
mb-3
"
>

❌ {w}

</p>


)

)

}


</div>


</div>









{/* HIRING */}


<div className="
mt-8
bg-slate-900
rounded-xl
p-8
text-center
">


<h2 className="
text-2xl
font-bold
mb-5
">

Hiring Recommendation

</h2>



<div className="
inline-block
px-8
py-3
rounded-full
bg-indigo-600
text-xl
font-bold
">

{

report.hiringRecommendation ||
"AI Pending"

}


</div>


</div>









{/* QUESTION ANALYSIS */}


<div className="
mt-8
bg-slate-900
rounded-xl
p-8
">


<h2 className="
text-2xl
font-bold
mb-6
">

Question Wise AI Analysis

</h2>




{

report.questions?.map(
(q,index)=>(


<div
key={index}
className="
border
border-slate-700
rounded-xl
p-5
mb-5
">


<h3 className="
text-indigo-400
font-bold
">

Question {index+1}

</h3>


<p className="mt-2">

{q.question}

</p>




<p className="
mt-4
text-green-400
font-semibold
">

Your Answer

</p>


<p className="text-gray-300">

{q.answer}

</p>




<p className="
mt-4
text-yellow-400
">

AI Score:
{q.score}/100

</p>




<p className="
text-gray-300
mt-2
">

{q.feedback}

</p>



</div>


)

)


}




</div>









<div className="
flex
justify-center
gap-5
mt-10
">


<button

onClick={()=>navigate("/hr/setup")}

className="
bg-indigo-600
px-6
py-3
rounded-xl
"

>

Retake Interview

</button>



<button

onClick={()=>navigate("/dashboard")}

className="
bg-gray-700
px-6
py-3
rounded-xl
"

>

Dashboard

</button>



</div>





</div>


</div>


);


}